### ISSUE TITLE
Why Any?

### ISSUE THREAD

**Issue by pftbest** [fiji-flo/gtmpl-rust#8]
Hello

Sorry for asking a stupid question, but I'm curious, why is `Arc<Any>` used everywhere? Can there be something other than `Value`?

**Comment by fiji-flo** [comment]
There used to be something other than `Value`. I wanted to keep the option open to use regular types for custom functions. Furthermore, I implemented `Value` rather late in the process and in the first version it needed to be `Any`.

However, I'm looking into replacing the `Arc<Any>` with `Value`. Restricting custom functions to 

`fn(&[Value]) -> Result<Value, String>` instead of `fn(&[Arc<Any>]) -> Result<Arc<Any>, String>` should be okay.

Help is welcome :D

**Comment by pftbest** [comment]
Oh, I've started replacing Arc<Any> today in the morning, and only now noticed that you did that work already :) Thank you.

**Comment by fiji-flo** [comment]
Sure. I screwed up one macro in `0.4.0`. I'll release `0.4.1` later today. If you're interested in contributing feel free to propose improvements and do an PR. Otherwise you might be interested to push for this https://github.com/fiji-flo/sprig-rust to become more stable.

**Comment by pftbest** [comment]
@fiji-flo Please update gtmpl_dervie to remove redundant copies, I've sent the pull requests.

**Comment by fiji-flo** [comment]
@pftbest Could you format your `gtmpl_derive` PR? I'm happy to merge and wait with the `0.4.1` release for this if you wanna change the version back `0.4.1` #10 (I didn't upload that release yet).

**Comment by pftbest** [comment]
@fiji-flo I've updated both PRs

**Comment by fiji-flo** [comment]
merged. Thanks for you help.

**Comment by pftbest** [comment]
Looks like everything works as expected. This can be closed now.

Thank you
